services:
  - type: web
    name: my-pywire-app
    runtime: docker
    plan: standard
    envVars:
      - key: REDIS_URL
        fromService:
          name: my-pywire-app-redis
          type: keyvalue
          property: connectionString

  - type: keyvalue
    name: my-pywire-app-redis
    plan: starter
    ipAllowList: []   # internal access only
